# Generated by Django 6.0.6 on 2026-06-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('0-100', '0-100 km/h'), ('0-200', '0-200 km/h'), ('100-200', '100-200 km/h'), ('400m', '400m (1/4 mile)')], max_length=10, verbose_name='Type of measurements')),
                ('time_seconds', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Time (seconds)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='garage.usercar')),
            ],
        ),
    ]
