# Generated by Django 6.0.6 on 2026-06-17 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='CarCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model and Generation')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='garage.brand')),
            ],
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(help_text='e.g., 340i, M550d', max_length=50, verbose_name='Engine / Modification')),
                ('year', models.IntegerField(verbose_name='Year of Release')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=15, verbose_name='Fuel Type')),
                ('stage', models.CharField(choices=[('Stock', 'Stock'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Stage 4', 'Stage 4')], default='Stock', max_length=10, verbose_name='Tuning Level')),
                ('specs', models.TextField(blank=True, verbose_name='Spec List / Modifications')),
                ('car_base', models.ForeignKey(help_text='Select the car model and generation from the catalog', on_delete=django.db.models.deletion.PROTECT, to='garage.carcatalog', verbose_name='Enter car model and generation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
